### ISSUE TITLE
Microbit V2

### ISSUE THREAD

**Issue by mmelgarejogit** [kd8bxp/micro-Maqueen-Arduino-Library#3]
I installed all the libraries mentioned, but when i select my board in the Arduino IDE (BBC microbit v2) and execute an example code i get an error, if i select the board BBC microbit ( i understand this is de v1) the code compile but nothing happens, i thing is an error of compatibility, because i can execute code for my microbit board but i cannot make it work with the maqueen robot, this library is compatible with the BBC microbit V2 board?

**Comment by kd8bxp** [comment]
Honestly I don't know, I don't have either the Micro Bit v2 or one of the newer Maqueen Robots.
from what you are asking, I would say no, the code will only work with the v1 Maqueen and original Micro Bit.

Sorry, I can't be much of a help. I probably should archive this repository as much has changed over the years.
